name: ONE Markdown Files

on:
  push:
    paths:
      - '**/*.md'  # Trigger on Markdown file changes
  workflow_dispatch:  # ✅ Manual trigger via GitHub UI

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: ONE .md files into ONE.md
        run: |
          output="ONE.md"
          echo "" > "$output"
          find . -type f -name "*.md" ! -name "$output" | sort | while read -r file; do
            if [[ "$file" == "./README.md" ]]; then
              # Just append the special file content as-is, no numbering
              cat "$file" >> "$output"
              echo -e "\n-------------\n" >> "$output"
            else
              # Number words for all other files
              tr ' ' '\n' < "$file" | nl -w1 -s'. ' >> "$output"
              echo -e "\n-------------\n" >> "$output"
            fi
          done

      - name: Commit and push ONE.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ONE.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Auto-update ONE.md after .md change"
          git push
