name: Append .md Files to README.md

on:
  push:
    branches:
      - main  # You can change this to whichever branch you want to trigger the workflow from
  workflow_dispatch:  # This allows manual trigger from GitHub UI

jobs:
  append-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Append markdown files to README.md
        run: |
          # Create a temporary section header for additional documentation
          echo -e "\n## Additional Documentation\n" >> README.md

          # Initialize a counter for numbering the files
          count=1

          # Loop over all .md files except README.md and append them to README.md
          for file in $(ls *.md | grep -v 'README.md' | sort -V); do
            # Append numbered list entry and file content to README.md
            echo -e "$count. **$file**" >> README.md
            cat "$file" >> README.md
            echo -e "\n---\n" >> README.md
            ((count++))
          done

      - name: Commit changes to README.md
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README.md with additional documentation"
          git push
