name: Combine Markdown Files

on:
  push:
    paths:
      - '**.md'  # Run when any Markdown file changes

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Combine .md files into combined.md
        run: |
          echo "" > combined.md
          for file in $(find . -type f -name "*.md" ! -name "one.md" | sort); do
            echo "### File: $file" >> combined.md
            echo "" >> combined.md
            cat "$file" >> combined.md
            echo -e "\n-------------\n" >> combined.md
          done

      - name: Commit and push combined.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add combined.md
          git commit -m "Auto-update combined.md after .md change" || echo "No changes to commit"
          git push
