name: ONE Markdown Files

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Regenerate README.md with appended .md files after marker
        run: |
          marker="<!-- APPENDED-CONTENT-START -->"
          temp_static="__static.md"
          temp_appended="__appended.md"
          combined_temp="__combined.md"
          output_readme="README.md"

          # Extract static content before marker
          awk "/$marker/{exit} {print}" "$output_readme" > "$temp_static"

          # Append the marker to static content
          echo -e "\n$marker\n" >> "$temp_static"

          # Generate appended content from other .md files
          echo "" > "$temp_appended"
          find . -type f -name "*.md" ! -name "README.md" | sort -V | while read -r file; do
            echo -e "\n### File: $(basename "$file")" >> "$temp_appended"
            cat "$file" >> "$temp_appended"
            echo -e "\n-------------\n" >> "$temp_appended"
          done

          # Combine static + appended content safely
          cat "$temp_static" "$temp_appended" > "$combined_temp"

          # Replace README.md with the new combined file
          mv "$combined_temp" "$output_readme"

          # Clean up temp files
          rm -f "$temp_static" "$temp_appended"

      - name: Commit and push updated README.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update README.md with appended .md files"
          git push
