name: Append Markdown Files to README

on:
  push:
    paths:
      - '**/*.md'  # Trigger on changes to Markdown files
  workflow_dispatch:  # Manual trigger option

jobs:
  append-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure the repo is available

      - name: Append all .md files to README.md
        run: |
          output="README.md"
          temp_append="__append.md"  # Temporary file to collect all the content

          # Step 1: Collect content from all .md files (excluding README.md) into a temporary file
          find . -type f -name "*.md" ! -name "README.md" | sort -V | xargs cat > "$temp_append"  # Concatenate contents

          # Step 2: Append the collected content to README.md
          echo -e "\n\n<!-- APPENDED CONTENT -->\n" >> "$output"  # Add a marker for where new content starts
          cat "$temp_append" >> "$output"  # Append the content from the temporary file

          # Step 3: Clean up the temporary file
          rm -f "$temp_append"

      - name: Commit and push updated README.md
        run: |
          git config --global user.name "github-actions"  # Set the username for the commit
          git config --global user.email "github-actions@github.com"  # Set the email for the commit
          git add README.md  # Stage the changes to README.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Append .md file contents to README.md"  # Commit changes if there are any
          git push  # Push the changes to the remote repository
