name: Combine Markdown Files

on:
  push:
    paths:
      - '**/*.md'  # Trigger only when .md files change

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Combine .md files into combined.md
        run: |
          output="one.md"
          echo "" > "$output"
          # Find all markdown files excluding 'combined.md'
          find . -type f -name "*.md" ! -name "$output" | sort | while read -r file; do
            echo "### File: $file" >> "$output"
            echo "" >> "$output"
            cat "$file" >> "$output"
            echo -e "\n-------------\n" >> "$output"
          done

      - name: Commit and push combined.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add combined.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Auto-update combined.md after .md change"
          git push
