name: Append Markdown Files to README

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  append-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Append all other .md files content to README.md
        run: |
          output="README.md"
          temp_append="__append.md"

          # Collect content of all md files except README.md into temp file
          find . -type f -name "*.md" ! -name "README.md" | sort -V | xargs cat > "$temp_append"

          # Append temp content to README.md only if it changes the file
          if ! tail -n +$(($(wc -l < "$output") + 1)) "$temp_append" | cmp -s - "$output"; then
            echo "" >> "$output"
            cat "$temp_append" >> "$output"
          fi

          rm -f "$temp_append"

      - name: Commit and push if README.md changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Append markdown files to README.md"
          git push

