name: ONE Markdown Files

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Regenerate README.md with appended .md files
        run: |
          marker="<!-- APPENDED-CONTENT-START -->"
          temp_static="__static.md"
          temp_appended="__appended.md"
          output_readme="README.md"

          # Extract static content (everything before the marker)
          awk "/$marker/{exit} {print}" "$output_readme" > "$temp_static"

          # Add the marker back at the end of static content
          echo -e "\n$marker\n" >> "$temp_static"

          # Create appended content from all other .md files (except README.md)
          echo "" > "$temp_appended"
          find . -type f -name "*.md" ! -name "README.md" | sort -V | while read -r file; do
            echo -e "\n### File: $(basename "$file")" >> "$temp_appended"
            cat "$file" >> "$temp_appended"
            echo -e "\n-------------\n" >> "$temp_appended"
          done

          # Combine static content + marker + appended content into README.md
          cat "$temp_static" "$temp_appended" > "$output_readme"

          # Cleanup temporary files
          rm -f "$temp_static" "$temp_appended"

      - name: Commit and push updated README.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update README.md with appended .md files"
          git push
