name: ONE Markdown Files

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Regenerate README.md with appended .md files
        run: |
          original_readme="README.md"
          temp_generated="__generated.md"
          final_combined="__combined.md"

          # Step 1: Generate combined content from all other .md files (except README.md)
          echo "" > "$temp_generated"
          find . -type f -name "*.md" ! -name "README.md" | sort -V | while read -r file; do
            echo -e "\n### File: $(basename "$file")" >> "$temp_generated"
            tr ' ' '\n' < "$file" | nl -w1 -s'. ' >> "$temp_generated"
            echo -e "\n-------------\n" >> "$temp_generated"
          done

          # Step 2: Concatenate original README.md + combined content into a new file
          cat "$original_readme" "$temp_generated" > "$final_combined"

          # Step 3: Overwrite README.md with the new combined file
          mv "$final_combined" "$original_readme"

          # Step 4: Clean up temporary generated file
          rm -f "$temp_generated"

      - name: Commit and push updated README.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update README.md with processed .md files"
          git push
