name: ONE Markdown Files

on:
  push:
    paths:
      - '**/*.md'  # Trigger on Markdown file changes
  workflow_dispatch:  # ✅ Manual trigger via GitHub UI

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Combine .md files into README.md
        run: |
          temp_output="temp_combined.md"
          echo "" > "$temp_output"
          
          find . -type f -name "*.md" ! -name "README.md" | sort -V | while read -r file; do
            echo "### File: $(basename "$file")" >> "$temp_output"
            tr ' ' '\n' < "$file" | nl -w1 -s'. ' >> "$temp_output"
            echo -e "\n-------------\n" >> "$temp_output"
          done
          
          # Append original README.md content
          cat README.md >> "$temp_output"

          # Replace README.md with new combined content
          mv "$temp_output" README.md

      - name: Commit and push updated README.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Auto-update README.md after .md change"
          git push
